CREATE TABLE "ELE_TRUNCADOS"
   (	"ID" NUMBER,
	"CODIGO" VARCHAR2(20 BYTE),
	"NUMERO" VARCHAR2(20 BYTE),
	"FECHA" DATE,
	"OBSERVACION" VARCHAR2(4000 BYTE)
   )
   TABLESPACE "USERS";

   ALTER TABLE "ELE_TRUNCADOS"
    ADD CONSTRAINT "PK_ELE_TRUNCADOS" PRIMARY KEY ( "ID" )
        USING INDEX TABLESPACE "USERS"
    ENABLE;

ALTER TABLE "ELE_TRUNCADOS" MODIFY (
    "ID"
        NOT NULL ENABLE
);
