grant select on gnr_datos_generales to quijotelui;
grant select on FAC_FACTURA_C to quijotelui;
grant select on V_CLIENTE to quijotelui;
grant execute on PKG_INFO_FACTURA to quijotelui;
grant execute on PKG_INFO_RETENCION to quijotelui;
grant select on FAC_FACTURA_D to quijotelui;
grant select on INV_PRODUCTOS to quijotelui;
grant select on INV_ARTICULO to quijotelui;
grant select on CXC_PAGO_CONTADO to quijotelui;
grant select on CXC_DOC_COBRAR to quijotelui;
grant select on GNR_PERSONA to quijotelui;
grant select on BAN_RETENCION_C to quijotelui;
grant select on V_PROVEEDOR to quijotelui;
grant select on BAN_RETENCION_D to quijotelui;
grant select on BAN_TIPO_RETENCION to quijotelui;
grant select on PED_DESPACHO_C to quijotelui;
grant select on PED_TRANSPORTISTA to quijotelui;
grant select on PED_DESPACHO_D to quijotelui;
grant select on FAC_DEVOLUCION_C to quijotelui;
grant select on CXC_ABONO_C to quijotelui;
grant execute on PKG_INFO_NOTA_CREDITO to quijotelui;
grant execute on FUN_GET_PORCENTAJE_IVA to quijotelui;
grant select on FAC_DEVOLUCION_D to quijotelui;
grant select on CXC_ABONO_D to quijotelui;
grant select on CXC_TIPO_MOTIVO to quijotelui;

--grant select on QUIJOTELUI.ELE_DOCUMENTOS_ELECTRONICOS to dismemayor;
--CREATE SYNONYM ELE_DOCUMENTOS_ELECTRONICOS FOR QUIJOTELUI.ELE_DOCUMENTOS_ELECTRONICOS;