  CREATE OR REPLACE FORCE VIEW V_ELE_CONTRIBUYENTES ("ID", "RAZON_SOCIAL", "NOMBRE_COMERCIAL", "RUC", "DIRECCION", "OBLIGADO_CONTABILIDAD", "CONTRIBUYENTE_ESPECIAL") AS
  SELECT rownum as id,TITULO5 AS Razon_Social,
    TITULO1      AS Nombre_Comercial,
    RUC,
    DIRECCION,
    TITULO2 as Obligado_Contabilidad,
    TITULO6 as Contribuyente_Especial
  FROM DISMEMAYOR.GNR_DATOS_GENERALES
  WHERE rownum=1;
