CREATE OR REPLACE FORCE VIEW V_ELE_GUIAS_RECEPTOR_DETALLE ("ID", "CODIGO", "NUMERO", "DOCUMENTO", "CODIGO_ARTICULO", "NOMBRE_ARTICULO", "CANTIDAD") AS 
  SELECT  rownum as ID,
dd.COD_DOCUMENTO AS CODIGO,
  TO_CHAR(dd.NUM_DESPACHO,'fm000000000000000') AS NUMERO,
  c.DOCUMENTO,
  to_char(fd.COD_ARTICULO) AS CODIGO_ARTICULO,
  a.NOMBRE_ARTICULO,
  SUM(fd.AUX_CANTIDAD) AS CANTIDAD
FROM DISMEMAYOR.PED_DESPACHO_D dd
INNER JOIN DISMEMAYOR.FAC_FACTURA_C fc
ON dd.COD_FACTURA  = fc.COD_DOCUMENTO
AND dd.NUM_FACTURA = fc.NUM_FACTURA
INNER JOIN DISMEMAYOR.FAC_FACTURA_D fd
ON fc.COD_EMPRESA    = fd.COD_EMPRESA
AND fc.COD_DOCUMENTO = fd.COD_DOCUMENTO
AND fc.NUM_FACTURA   = fd.NUM_FACTURA
INNER JOIN DISMEMAYOR.INV_ARTICULO a
ON fd.COD_ARTICULO = a.COD_ARTICULO
INNER JOIN DISMEMAYOR.V_CLIENTE c
ON c.COD_CLIENTE = fc.COD_CLIENTE
where dd.COD_DOCUMENTO = 'GUI'
GROUP BY rownum,dd.COD_DOCUMENTO,
  dd.NUM_DESPACHO,
  c.DOCUMENTO,
  fd.COD_ARTICULO,
  a.NOMBRE_ARTICULO;