CREATE TABLE ele_documentos_electronicos (
    "ID"                    NUMBER
        NOT NULL ENABLE,
    "CODIGO"                VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "NUMERO"                VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "NUMERO_AUTORIZACION"   VARCHAR2(100 BYTE),
    "FECHA_AUTORIZACION"    VARCHAR2(100 BYTE),
    "OBSERVACION"           VARCHAR2(4000 BYTE),
    "ESTADO"                VARCHAR2(20 BYTE),
    CONSTRAINT "PK_ELE_DOCUMENTO_ELECTRONICO" PRIMARY KEY ( "ID" )
        USING INDEX TABLESPACE "USERS"
    ENABLE,
    CONSTRAINT "UK_ELE_DOCUMENTO_ELECTRONICO" UNIQUE ( "CODIGO","NUMERO" )
        USING INDEX TABLESPACE "USERS"
    ENABLE
)
    TABLESPACE "USERS";