CREATE OR REPLACE FORCE VIEW V_ELE_GUIAS ("ID", "ID_CONTRIBUYENTE", "CODIGO", "NUMERO", "CODIGO_DOCUMENTO", "ESTABLECIMIENTO", "PUNTO_EMISION", "SECUENCIAL", "FECHA", "FECHA_FIN", "DIRECCION_PARTIDA", "RAZON_SOCIAL_TRANSPORTISTA", "TIPO_DOCUMENTO", "DOCUMENTO", "PLACA", "DIRECCION_ESTABLECIMIENTO") AS
  SELECT p.NUM_DESPACHO as id,
  1 as id_contribuyente,
p.COD_DOCUMENTO AS CODIGO,
  TO_CHAR(p.NUM_DESPACHO ,'fm000000000000000') AS NUMERO,
  cast('06' as varchar2(2)) codigo_documento,
   DECODE(SUBSTR(TO_CHAR(p.NUM_DESPACHO, 'fm000000000000000'), 1, 3), '000', '001', SUBSTR(TO_CHAR(p.NUM_DESPACHO, 'fm000000000000000'), 1, 3)) establecimiento,
  DECODE(SUBSTR(TO_CHAR(p.NUM_DESPACHO, 'fm000000000000000'), 4, 3), '000', '001', SUBSTR(TO_CHAR(p.NUM_DESPACHO, 'fm000000000000000'), 4, 3)) punto_emision,
  TO_CHAR(SUBSTR(TO_CHAR(p.NUM_DESPACHO, 'fm000000000000000'), 7, 9)) secuencial,
  trunc(p.FECHA_DESPACHO) AS FECHA,
  trunc(p.FECHA_DESPACHO +5) AS FECHA_FIN,
  t.DIRECCION AS DIRECCION_PARTIDA,
  t.NOMBRES AS RAZON_SOCIAL_TRANSPORTISTA,
  DECODE(t.CEDULA, '9999999999999', '07', DECODE(LENGTH(t.CEDULA), 13, '04', 10, '05', '06')) AS tipo_documento,
  t.CEDULA AS DOCUMENTO,
  t.COMENTARIO AS PLACA,
    (SELECT DIRECCION FROM V_ELE_CONTRIBUYENTES) as direccion_establecimiento
FROM dismemayor.PED_DESPACHO_C p
INNER JOIN dismemayor.PED_TRANSPORTISTA t
ON p.COD_TRANSPORTISTA = t.COD_TRANSPORTISTA
where p.ESTADO='C'
and p.COD_DOCUMENTO='GUI';
