CREATE OR REPLACE FORCE VIEW "V_ELE_GUIAS_RECEPTOR" ("ID", "CODIGO", "NUMERO", "DOCUMENTO", "RAZON_SOCIAL", "DIRECCION", "MOTIVO_TRASLADO") AS
  SELECT  rownum as ID,
  dd.COD_DOCUMENTO AS CODIGO,
TO_CHAR(dd.NUM_DESPACHO,'fm000000000000000') AS NUMERO,
c.DOCUMENTO,
  c.RAZON_SOCIAL AS RAZON_SOCIAL,
  c.DIRECCION,
  cast('Venta de productos' as varchar2(18)) as MOTIVO_TRASLADO
FROM DISMEMAYOR.PED_DESPACHO_D dd
INNER JOIN DISMEMAYOR.FAC_FACTURA_C f
ON dd.COD_FACTURA  = f.COD_DOCUMENTO
AND dd.NUM_FACTURA = f.NUM_FACTURA
INNER JOIN DISMEMAYOR.V_CLIENTE c
ON f.COD_CLIENTE = c.COD_CLIENTE
WHERE dd.COD_DOCUMENTO='GUI';