CREATE OR REPLACE FORCE VIEW V_ELE_RETENCIONES_DETALLE ("ID", "CODIGO", "NUMERO", "TIPO", "CODIGO_SRI", "BASE_IMPONIBLE", "PORCENTAJE", "VALOR_RETENIDO", "TIPO_COMPROBANTE", "NUMERO_COMPROBANTE", "FECHA_COMPROBANTE") AS 
  SELECT rownum as ID,
  CAST( 'RET' AS varchar2(3) ) AS codigo,
  TO_CHAR(dr.NUM_RETENCION,'fm000000000000000') AS numero,
  decode(tr.TIPO_IMPUESTO,'RENTA',1,'IVA',2,0) as TIPO,
  decode(tr.TIPO_IMPUESTO,'RENTA',tr.COD_SRI ,'IVA',DECODE(PORC_RETENCION,10,'9',20,'10',30,'1',70,'2',100,'3','0'),'0') as CODIGO_SRI,
  dr.VALOR_BASE as BASE_IMPONIBLE,
  dr.PORC_RETENCION AS PORCENTAJE,
  dr.VALOR_RETENIDO,
  DISMEMAYOR.PKG_INFO_RETENCION.FUN_GET_TIPO_COMPROBANTE(dr.NUM_RETENCION) TIPO_COMPROBANTE,
  DISMEMAYOR.PKG_INFO_RETENCION.FUN_NUMERO_COMPROBANTE(dr.NUM_RETENCION) NUMERO_COMPROBANTE,
  DISMEMAYOR.PKG_INFO_RETENCION.FUN_FECHA_COMPROBANTE(dr.NUM_RETENCION) FECHA_COMPROBANTE
FROM DISMEMAYOR.BAN_RETENCION_D dr
INNER JOIN DISMEMAYOR.BAN_TIPO_RETENCION tr
ON dr.COD_RETENCION = tr.COD_RETENCION;
